In [27]:
%pip install pandas numpy tqdm regex rapidfuzz

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (2025.11.3)
Requirement already satisfied: rapidfuzz in /usr/local/lib/python3.12/dist-packages (3.14.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [28]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [29]:
#==========================================================
# IMPORT LIBRARIES
#==========================================================

import os
import re
import csv
import json
import logging
import warnings

import pandas as pd
import numpy as np

from tqdm import tqdm
from glob import glob
from rapidfuzz import fuzz

warnings.filterwarnings("ignore")

In [30]:
#==========================================================
# INITIALIZE DIRECTORY
#==========================================================

ROOT_DIR = "/content/drive/MyDrive/2023-453_PenalaranKomputerB/SubCPMK3/perikanan"

PATH_RAW = os.path.join(
    ROOT_DIR,
    "data",
    "raw_text"
)

PATH_PROCESSED = os.path.join(
    ROOT_DIR,
    "data",
    "processed"
)

PATH_CSV = os.path.join(
    PATH_PROCESSED,
    "cases.csv"
)

PATH_JSON = os.path.join(
    PATH_PROCESSED,
    "cases.json"
)

LOG_DIR = os.path.join(
    ROOT_DIR,
    "logs"
)

LOG_PATH = os.path.join(
    LOG_DIR,
    "metadata_extraction.log"
)

os.makedirs(PATH_PROCESSED, exist_ok=True)
os.makedirs(LOG_DIR, exist_ok=True)

print("ROOT DIR :", ROOT_DIR)
print("RAW TEXT :", PATH_RAW)
print("CSV PATH :", PATH_CSV)

ROOT DIR : /content/drive/MyDrive/2023-453_PenalaranKomputerB/SubCPMK3/perikanan
RAW TEXT : /content/drive/MyDrive/2023-453_PenalaranKomputerB/SubCPMK3/perikanan/data/raw_text
CSV PATH : /content/drive/MyDrive/2023-453_PenalaranKomputerB/SubCPMK3/perikanan/data/processed/cases.csv

In [31]:
#==========================================================
# INITIALIZE LOGGING
#==========================================================

for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

logging.basicConfig(

    filename=LOG_PATH,

    level=logging.INFO,

    format="%(asctime)s | %(levelname)s | %(message)s",

    filemode="w"
)

logging.info("===== NOTEBOOK 02 STARTED =====")

In [32]:
#==========================================================
# NATURAL SORT
#==========================================================

def natural_sort_key(path):

    filename = os.path.basename(path)

    numbers = re.findall(r'\d+', filename)

    return int(numbers[0]) if numbers else 0

In [33]:
#==========================================================
# LOAD TXT FILES
#==========================================================

text_files = glob(
    os.path.join(PATH_RAW, "*.txt")
)

text_files = sorted(
    text_files,
    key=natural_sort_key
)

print(f"TOTAL TXT FILES : {len(text_files)}")

logging.info(
    f"TOTAL TXT FILES : {len(text_files)}"
)

TOTAL TXT FILES : 30

In [34]:
#==========================================================
# TEXT CLEANING
#==========================================================
def normalize_text(text):

    if pd.isna(text):
        return ""

    text = str(text)

    patterns = [

        r'Direktori Putusan.*?RI',

        r'Mahkamah Agung Republik Indonesia',

        r'putusan\.mahkamahagung\.go\.id',

        r'Disclaimer',

        r'Kepaniteraan.*?RI',

        r'Email\s*:.*',

        r'Telp\s*:.*',

        r'Hal\.\s*\d+',

        r'waktu kewaktu.*?hubungi melalui',

        r'dalam hal anda menemukan inakurasi informasi.*?hubungi melalui',

        r'halaman \d+ dari \d+ hal',

    ]

    for pattern in patterns:

        text = re.sub(
            pattern,
            ' ',
            text,
            flags=re.IGNORECASE
        )

    text = re.sub(r'\s+', ' ', text)

    return text.strip()

In [35]:
#==========================================================
# EXTRACT NOMOR PUTUSAN
#==========================================================

def clean_nomor_putusan(text):

    text = text.upper()

    text = text.replace(
        "PID. SUS",
        "PID.SUS"
    )

    text = re.sub(
        r'[^A-Z0-9./\-]',
        '',
        text
    )

    return text.strip()


def extract_nomor_putusan(text):

    patterns = [

        r'Nomor\s*:?\s*([0-9]+[\w./\-]+)',

        r'PUTUSAN\s+Nomor\s*:?\s*([0-9]+[\w./\-]+)',

        r'([0-9]+K/PID\.?SUS/[0-9]{4})',

        r'([0-9]+/Pid\.[A-Za-z./\-]+/[0-9]{4}/PN\.[A-Za-z]+)',

        r'([0-9]{1,5}/[A-Za-z0-9.\-]+/[0-9]{4})',
    ]

    candidates = []

    for pattern in patterns:

        matches = re.findall(
            pattern,
            text[:10000],
            re.IGNORECASE
        )

        for match in matches:

            nomor = clean_nomor_putusan(match)

            if "/" in nomor:
                candidates.append(nomor)

    candidates = list(dict.fromkeys(candidates))

    if candidates:

        candidates = sorted(
            candidates,
            key=len,
            reverse=True
        )

        return candidates[0]

    return "Tidak ditemukan"

In [36]:
#==========================================================
# EXTRACT TAHUN
#==========================================================

def extract_tahun(text):

    match = re.search(
        r'/(\d{4})/',
        text
    )

    if match:
        return match.group(1)

    return "Tidak ditemukan"

In [37]:
#==========================================================
# EXTRACT PENGADILAN
#==========================================================

def extract_pengadilan(text):

    patterns = [

        r'Pengadilan Negeri\s+[A-Za-z]+',

        r'Pengadilan Tinggi\s+[A-Za-z]+',
    ]

    for pattern in patterns:

        match = re.search(
            pattern,
            text,
            re.IGNORECASE
        )

        if match:

            hasil = match.group(0)

            hasil = re.sub(
                r'(karena|yang|dan).*',
                '',
                hasil,
                flags=re.IGNORECASE
            )

            return hasil.strip()

    if "Mahkamah Agung" in text:
        return "Mahkamah Agung"

    return "Tidak ditemukan"

In [38]:
#==========================================================
# EXTRACT TERDAKWA
#==========================================================

def clean_name(name):

    name = name.upper()

    stopwords = [

        "TEMPAT LAHIR",

        "UMUR",

        "TANGGAL LAHIR",

        "JENIS KELAMIN",

        "KEBANGSAAN",

        "TEMPAT TINGGAL",

        "AGAMA",

        "PEKERJAAN",
    ]

    for stop in stopwords:

        if stop in name:
            name = name.split(stop)[0]

    name = re.sub(
        r'[^A-Z\s.]',
        ' ',
        name
    )

    name = re.sub(
        r'\s+',
        ' ',
        name
    )

    return name.strip()


def extract_terdakwa(text):

    hasil = []

    patterns = [

        r'Nama lengkap\s*:\s*(.*?);',

        r'Nama\s*:\s*(.*?);',

        r'Terdakwa\s*:\s*(.*?);',
    ]

    for pattern in patterns:

        matches = re.findall(
            pattern,
            text[:15000],
            re.IGNORECASE | re.DOTALL
        )

        for match in matches:

            nama = clean_name(match)

            if len(nama) > 3:
                hasil.append(nama)

    hasil = list(dict.fromkeys(hasil))

    if hasil:
        return " | ".join(hasil[:10])

    return "Tidak ditemukan"

In [39]:
#==========================================================
# EXTRACT PASAL
#==========================================================

def extract_pasal(text):

    patterns = [

        r'pasal\s+\d+\s+ayat\s+\(\d+\)',

        r'pasal\s+\d+',
    ]

    hasil = []

    for pattern in patterns:

        matches = re.findall(
            pattern,
            text,
            re.IGNORECASE
        )

        hasil.extend(matches)

    hasil = list(set(hasil))

    if hasil:
        return "; ".join(hasil[:10])

    return "Tidak ditemukan"

In [40]:
#==========================================================
# EXTRACT DAKWAAN
#==========================================================

def extract_dakwaan(text):

    keywords = [

        "didakwa",

        "dakwaan",

        "kesatu",
    ]

    lower = text.lower()

    for keyword in keywords:

        idx = lower.find(keyword)

        if idx != -1:

            chunk = text[idx:idx+5000]

            chunk = normalize_text(chunk)

            if len(chunk) > 100:
                return chunk

    return "Tidak ditemukan"

In [41]:
# =========================================================
# EXTRACT RINGKASAN FAKTA
# =========================================================

def extract_ringkasan_fakta(text):

    text_lower = text.lower()

    patterns = [

        r'bahwa terdakwa.*?(?=menimbang)',

        r'berawal dari.*?(?=menimbang)',

        r'pada hari.*?(?=menimbang)',

        r'telah melakukan.*?(?=menimbang)',

        r'jaksa penuntut umum.*?(?=menimbang)',

        r'didakwa.*?(?=menimbang)',

        r'uraian kejadian.*?(?=menimbang)',
    ]

    for pattern in patterns:

        match = re.search(

            pattern,

            text_lower,

            re.DOTALL | re.IGNORECASE
        )

        if match:

            fakta = match.group(0)

            fakta = re.sub(r'\s+', ' ', fakta)

            fakta = fakta.strip()

            if len(fakta) > 100:

                logging.info(
                    f"Ringkasan fakta ditemukan"
                )

                return fakta[:1500]

    logging.warning(
        "Ringkasan fakta tidak ditemukan"
    )

    return ""

In [42]:
#==========================================================
# EXTRACT AMAR PUTUSAN
#==========================================================

def extract_amar_putusan(text):

    keywords = [

        "mengadili",

        "memutuskan",

        "menyatakan terdakwa",
    ]

    lower = text.lower()

    for keyword in keywords:

        idx = lower.find(keyword)

        if idx != -1:

            chunk = text[idx:idx+4000]

            chunk = normalize_text(chunk)

            if len(chunk) > 100:
                return chunk

    return "Tidak ditemukan"

In [43]:
#==========================================================
# EXTRACT JENIS PUTUSAN
#==========================================================

def extract_jenis_putusan(text):

    text = text.lower()

    if any(k in text for k in [
        "bom",
        "bahan peledak",
        "peledak"
    ]):
        return "Bom Ikan"

    if any(k in text for k in [
        "trawl",
        "pukat harimau"
    ]):
        return "Trawl"

    if "sipi" in text:
        return "Tanpa SIPI"

    if "siup" in text:
        return "Tanpa SIUP"

    if "spb" in text:
        return "Tanpa SPB"

    if any(k in text for k in [
        "vietnam",
        "thailand",
        "asing"
    ]):
        return "Kapal Asing"

    if "illegal fishing" in text:
        return "Illegal Fishing"

    return "Perikanan Umum"

In [44]:
#==========================================================
# BUILD DATASET
#==========================================================

dataset = []

for file_path in tqdm(text_files):

    filename = os.path.basename(file_path)

    logging.info(
        f"PROCESSING : {filename}"
    )

    try:

        with open(
            file_path,
            "r",
            encoding="utf-8"
        ) as f:

            text = f.read()

    except:

        with open(
            file_path,
            "r",
            encoding="latin-1"
        ) as f:

            text = f.read()

    text = normalize_text(text)

    case_data = {

        "case_id":
        filename.replace(".txt", ""),

        "nomor_putusan":
        extract_nomor_putusan(text),

        "tahun":
        extract_tahun(text),

        "pengadilan":
        extract_pengadilan(text),

        "terdakwa":
        extract_terdakwa(text),

        "pasal":
        extract_pasal(text),

        "jenis_putusan":
        extract_jenis_putusan(text),

        "dakwaan":
        extract_dakwaan(text),

        "ringkasan_fakta":
        extract_ringkasan_fakta(text),

        "amar_putusan":
        extract_amar_putusan(text),

        "full_text":
        text
    }

    dataset.append(case_data)

    logging.info(
        f"SUCCESS : {filename}"
    )

print("DATASET CREATED")

100%|██████████| 30/30 [00:01<00:00, 28.18it/s]

DATASET CREATED

In [45]:
#==========================================================
# CREATE DATAFRAME
#==========================================================

df = pd.DataFrame(dataset)
df["retrieval_topic"] = df["jenis_putusan"]

print(df.shape)

df.head()

(30, 12)

,case_id,nomor_putusan,tahun,pengadilan,terdakwa,pasal,jenis_putusan,dakwaan,ringkasan_fakta,amar_putusan,full_text,retrieval_topic
0,case_001,1105/2016/S.270/TAH.SUS.IK/PP/2016/MATANGGAL29,2016,Pengadilan Negeri sejak,SOPIAN BINRABBIL | SARIF BINCU | SAMSULBINKOHE...,Pasal 8 ayat (1); Pasal 9; Pasal 46; Pasal 39;...,Bom Ikan,didakwa:KESATU :BahwaTerdakwaISOPIAN binRABBIL...,pada hari senin tanggal 02 nopember 2015sekira...,"mengadili,“Mereka yang melakukan, yang menyuru...",: Halaman 1 dari13hal. Put. Nomor :497K/Pid.Su...,Bom Ikan
1,case_002,7/AKTA-KASASI.PID.SUS-PRK/2017/PN.MDN,2017,Pengadilan Negeri Me,RIZAL | NAMA RIZAL,Pasal 9 ayat (1); Pasal 85; Pasal 98; Pasal 9,Trawl,didakwa dengan dakwaan sebagai berikut:Dakwaan...,bahwa terdakwa melanggar pasal 98 undang-undan...,MENGADILI SENDIRI:1.Menyatakan Terdakwa Rizal ...,: Halaman 1 PUTUSANNomor 102 K/Pid.Sus/2018DEM...,Trawl
2,case_003,3370/2016/S.853.TAH.SUS.IK/PP/2016/MA.TANGGAL,2016,Pengadilan Negeri Palembang,GINDA PURNAMABIN TEGIN | NAMA GINDA PURNAMABIN...,Pasal 30; Pasal 162; Pasal 253 Ayat (1); Pasal...,Trawl,didakwa dengan dakwaan sebagai berikut :Bahwa ...,"pada hari kamis,tanggal 4 februari 2016 sekira...",mengadili Pengadilan NegeriPalembang dikarenak...,: Halaman 1 dari18hal. Put. No.1442K/PID.SUS/2...,Trawl
3,case_004,88/PID.SUS/2015/PN.WNO.,2015,Pengadilan Negeri Wonosari,N A M A LENGKAP SUGIANTORO BIN SAINO ALIAS GIANTO,pasal 42 ayat (3); pasal 27 ayat (1); pasal 98...,Tanpa SIPI,didakwa sebagai berikut : Kesatu: Bahwa terdak...,bahwa terdakwa sugiyantoro als. giyanto bin sa...,mengadili Perkara Pidana dalam tingkat banding...,: Halaman 1 Nomor 84/PID.SUS/2015/PT YYK. PUTU...,Tanpa SIPI
4,case_005,24/AKTA.PID.SUS-PRK/2018/PNRANJUNCTONOMOR,2018,Pengadilan Negeri Ranai,TRAN VAN TRUONG | NAMA TRAN VAN TRUONG,Pasal 9; Pasal 102; Pasal 55; Pasal 92; Pasal ...,Trawl,didakwa dengan dakwaan sebagai berikut:-Kesatu...,bahwa terdakwa mengakuibelumpernah dihukum sed...,mengadili sendiri perkara inidengan amar putus...,: Halaman 1 dari9hal. Putusan Nomor1335K/Pid.S...,Trawl

In [46]:
#==========================================================
# SAVE CSV
#==========================================================

df.to_csv(

    PATH_CSV,

    index=False,

    encoding="utf-8-sig"
)

print("CSV SAVED")

logging.info(
    f"CSV SAVED : {PATH_CSV}"
)

CSV SAVED

In [47]:
#==========================================================
# SAVE JSON
#==========================================================

with open(
    PATH_JSON,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        dataset,
        f,
        ensure_ascii=False,
        indent=4
    )

print("JSON SAVED")

logging.info(
    f"JSON SAVED : {PATH_JSON}"
)

JSON SAVED

In [48]:
#==========================================================
# DATA QUALITY CHECK
#==========================================================

print("="*60)
print("DATASET SHAPE")
print("="*60)

print(df.shape)

print("\n")

print("="*60)
print("MISSING VALUES")
print("="*60)

print(df.isnull().sum())

print("\n")

print("="*60)
print("JENIS PUTUSAN")
print("="*60)

print(
    df["jenis_putusan"].value_counts()
)

============================================================
DATASET SHAPE
============================================================
(30, 12)


============================================================
MISSING VALUES
============================================================
case_id            0
nomor_putusan      0
tahun              0
pengadilan         0
terdakwa           0
pasal              0
jenis_putusan      0
dakwaan            0
ringkasan_fakta    0
amar_putusan       0
full_text          0
retrieval_topic    0
dtype: int64


============================================================
JENIS PUTUSAN
============================================================
jenis_putusan
Bom Ikan          8
Trawl             8
Tanpa SIPI        8
Perikanan Umum    3
Kapal Asing       2
Tanpa SIUP        1
Name: count, dtype: int64

In [49]:
#==========================================================
# SAMPLE RESULT
#==========================================================

sample = df.iloc[0]

for col in df.columns:

    print("="*80)

    print(col.upper())

    print("="*80)

    print(
        str(sample[col])[:2000]
    )

    print("\n")

================================================================================
CASE_ID
================================================================================
case_001


================================================================================
NOMOR_PUTUSAN
================================================================================
1105/2016/S.270/TAH.SUS.IK/PP/2016/MATANGGAL29


================================================================================
TAHUN
================================================================================
2016


================================================================================
PENGADILAN
================================================================================
Pengadilan Negeri sejak


================================================================================
TERDAKWA
================================================================================
SOPIAN BINRABBIL | SARIF BINCU | SAMSULBINKOHER | I.NAMA LENGKAP SOPIAN BINRABBIL


================================================================================
PASAL
================================================================================
Pasal 8 ayat (1); Pasal 9; Pasal 46; Pasal 39; Pasal 55; Pasal 84 ayat (1); Pasal 9 ayat (1); Pasal 55 ayat (1); Pasal 85; Pasal 76


================================================================================
JENIS_PUTUSAN
================================================================================
Bom Ikan


================================================================================
DAKWAAN
================================================================================
didakwa:KESATU :BahwaTerdakwaISOPIAN binRABBIL,TerdakwaIISARIF bin CUdanTerdakwaIIISAMSUL bin KOHER, pada hari Senin tanggal 02 Nopember 2015sekira pukul 12.15 wita atau setidak-tidaknya pada suatu waktu tertentu dalambulan Nopember tahun 2015, bertempat di Perairan laut Kandolo BontangKalimantan Timur atau setidak-tidaknya pada suatu tempat lain yang masihtermasuk dalam daerah hukum Pengadilan Negeri Bontang yang berwenangmemeriksa dan mengadili,“Mereka yang melakukan, yang menyuruhmelakukan, dan yang turut serta melakukan perbuatan yang dengan sengaja diwilayah pengelolaan perikanan Republik Indonesia melakukan penangkapan : Halaman 3 dari13hal. Put. Nomor :497K/Pid.Sus/2016ikan dan/atau pembudidayaan ikan dengan menggunakan bahan kimia, bahanbiologis, bahan peledak, alat dan/atau cara, dan/atau bangunan yang dapatmerugikan dan/atau membahayakan kelestarian sumber daya ikan dan/ ataulingkungannya sebagaimana dimaksud dalam Pasal 8 ayat (1) sebagaimanaSetiap orang dilarang melakukan penangkapan ikan dan/atau pembudidayaanikan dengan menggunakan bahan kimia, bahan biologis, bahanpeledak, alatdan/atau cara, dan/atau bangunan yang dapat merugikan dan/ataumembahayakan kelestarian sumber daya ikan dan/atau lingkungannya diwilayah pengelolaan perikanan Republik Indonesia”, perbuatan paraTerdakwadilakukan dengan cara-cara sebagaiberikut :-Berawal pada hari Senin tanggal 02 Nopember 2015 sekira pukul 11.00Wita,TerdakwaI SOPIAN bin RABBIL bersama-samaTerdakwaII SARIFbin CU danTerdakwaIII SAMSUL bin KOHER, dengan menggunakan kapalKetinting bertolak dari belakang rumahTerdakwaI di Bontang Kuala menujuke Perairan Kandolo Bontang dengan maksud untuk mancari ikan di lautdengan membawa peralatan berupa 1 (satu) unit compressor, selangdengan panjang lebih kurang 20 M (dua puluh meter), 2 (dua) pasang sepatukatak, 2 (dua) buah kaca mata, 1 (satu) buah Mouth fish, 1 (satu) buahkarung jaring, 3 (tiga) buah botol bir hitam kecil, campuran belerang, kepalakorek api dan cat perak½botol


================================================================================
RINGKASAN_FAKTA
================================================================================
pada hari senin tanggal 02 nopember 2015sekira pukul 12.15 wita atau setidak-tidaknya pada suatu waktu tertentu dalambulan nopember tahun 2015, bertempat di perairan laut kandolo bontangkalimantan timur atau setidak-tidaknya pada suatu tempat lain yang masihtermasuk dalam daerah hukum pengadilan negeri bontang yang berwenangmemeriksa dan mengadili,“mereka yang melakukan, yang menyuruhmelakukan, dan yang turut serta melakukan perbuatan yang dengan sengaja diwilayah pengelolaan perikanan republik indonesia melakukan penangkapan : halaman 3 dari13hal. put. nomor :497k/pid.sus/2016ikan dan/atau pembudidayaan ikan dengan menggunakan bahan kimia, bahanbiologis, bahan peledak, alat dan/atau cara, dan/atau bangunan yang dapatmerugikan dan/atau membahayakan kelestarian sumber daya ikan dan/ ataulingkungannya sebagaimana dimaksud dalam pasal 8 ayat (1) sebagaimanasetiap orang dilarang melakukan penangkapan ikan dan/atau pembudidayaanikan dengan menggunakan bahan kimia, bahan biologis, bahanpeledak, alatdan/atau cara, dan/atau bangunan yang dapat merugikan dan/ataumembahayakan kelestarian sumber daya ikan dan/atau lingkungannya diwilayah pengelolaan perikanan republik indonesia”, perbuatan paraterdakwadilakukan dengan cara-cara sebagaiberikut :-berawal pada hari senin tanggal 02 nopember 2015 sekira pukul 11.00wita,terdakwai sopian bin rabbil bersama-samaterdakwaii sarifbin cu danterdakwaiii samsul bin koher, dengan menggunakan kapalketinting bertolak dari belakang rumahterdakwai di bon


================================================================================
AMAR_PUTUSAN
================================================================================
mengadili,“Mereka yang melakukan, yang menyuruhmelakukan, dan yang turut serta melakukan perbuatan yang dengan sengaja diwilayah pengelolaan perikanan Republik Indonesia melakukan penangkapan : Halaman 3 dari13hal. Put. Nomor :497K/Pid.Sus/2016ikan dan/atau pembudidayaan ikan dengan menggunakan bahan kimia, bahanbiologis, bahan peledak, alat dan/atau cara, dan/atau bangunan yang dapatmerugikan dan/atau membahayakan kelestarian sumber daya ikan dan/ ataulingkungannya sebagaimana dimaksud dalam Pasal 8 ayat (1) sebagaimanaSetiap orang dilarang melakukan penangkapan ikan dan/atau pembudidayaanikan dengan menggunakan bahan kimia, bahan biologis, bahanpeledak, alatdan/atau cara, dan/atau bangunan yang dapat merugikan dan/ataumembahayakan kelestarian sumber daya ikan dan/atau lingkungannya diwilayah pengelolaan perikanan Republik Indonesia”, perbuatan paraTerdakwadilakukan dengan cara-cara sebagaiberikut :-Berawal pada hari Senin tanggal 02 Nopember 2015 sekira pukul 11.00Wita,TerdakwaI SOPIAN bin RABBIL bersama-samaTerdakwaII SARIFbin CU danTerdakwaIII SAMSUL bin KOHER, dengan menggunakan kapalKetinting bertolak dari belakang rumahTerdakwaI di Bontang Kuala menujuke Perairan Kandolo Bontang dengan maksud untuk mancari ikan di lautdengan membawa peralatan berupa 1 (satu) unit compressor, selangdengan panjang lebih kurang 20 M (dua puluh meter), 2 (dua) pasang sepatukatak, 2 (dua) buah kaca mata, 1 (satu) buah Mouth fish, 1 (satu) buahkarung jaring, 3 (tiga) buah botol bir hitam kecil, campuran belerang, kepalakorek api dan cat perak½botol coca cola ukuran½liter, 16 (enam belas)buah sumbu dan 1 (satu) korek gas, setibanya di perairan Kandolo sekitarpukul 12.00 wita,TerdakwaI dengan menggunakan kacamata dan sepatukatak langsung menyelam kedalam air untuk melihat ikan didalam air danmendapati banyak ikan didalam air, kemudianTerdakwaI naik kembalikeatas kapal ketinting dansekitar pukul 12.15 witaTerdakwaII langsungmelemparkan bom ikan atau bahan peledak yang telah dirakit ol


================================================================================
FULL_TEXT
================================================================================
: Halaman 1 dari13hal. Put. Nomor :497K/Pid.Sus/2016P U T U S A NNomor :497K/PID.SUS/2016DEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESAM A H K A M A H A G U N Gmemeriksa perkarapidana khususdalam tingkat kasasi telah memutuskansebagai berikut dalam perkaraParaTerdakwa:I.Nama lengkap:SOPIAN BinRABBIL;Tempat lahir:Toli-toli;Umur/tanggal lahir:36tahun/17 Juni 1979;Jenis Kelamin:Laki-laki;Kebangsaan:Indonesia;Tempat tinggal:Jalan Kapten Piere Tendean, Gang BatuSahasa 5 RT. 012 Kelurahan Bontang Kuala,Kecamatan BontangUtara, Kota Bontang;Agama:Islam;Pekerjaan:Nelayan;II.Nama lengkap:SARIF BinCU;Tempat lahir:Toli-toli;Umur/tanggal lahir:25tahun/31 Desember 1990;Jenis Kelamin:Laki-laki;Kebangsaan:Indonesia;Tempat tinggal:Labuan Lobo RT.001/ DesaLabuan Lobo,Kecamatan Ogodeide,Kabupaten Toli-toli,Sulawesi Tengah;Agama:Islam;Pekerjaan:Nelayan;III.Nama lengkap:SAMSULBinKOHER;Tempat lahir:Toli-toli;Umur/tanggal lahir:32tahun/30 Desember 1982;Jenis Kelamin:Laki-laki;Kebangsaan:Indonesia;Tempat tinggal:Jalan BatuSahasa5RT.011 KelurahanBontang Kuala,Kecamatan Bontang Utara,Kota Bontang;Agama:Islam; : Halaman 2 dari13hal. Put. Nomor :497K/Pid.Sus/2016Pekerjaan:Nelayan;ParaTerdakwaditahan di Rumah Tahanan Negara oleh :1.Penyidik sejak tanggal 4 Nopember 2015 sampai dengan tanggal 23Nopember 2015 ;2.Perpanjangan Penuntut Umum sejak tanggal 24 Nopember 2015 sampaidengan tanggal 3 Desember 2015 ;3.Penuntut Umum sejak tanggal 1 Desember 2015 sampai dengan tanggal 10Desember 2015 ;4.Penahanan MajelisHakimsejak tanggal 10 Desember 2015 sampai dengantanggal 29 Desember 2015 ;5.Perpanjangan oleh Ketua Pengadilan Negeri sejak tanggal 30 Desember2015 sampai dengan tanggal 8 Januari 2016;6.HakimPengadilan Tinggi Samarinda, sejak tanggal 6 Januari 2016 sampaidengan 25 Januari 2016 ;7.Perpanjangan oleh Ketua Pengadilan Tinggi Samarinda, sejak tanggal 26Januari 2016 sampai dengan 4 Pebruari 2016;8.BerdasarkanPenetapan Ketua u.b.Ketua Muda PidanaNomor :1105/2016/S.270/Tah.Sus.Ik/PP/2016/MAtangg


================================================================================
RETRIEVAL_TOPIC
================================================================================
Bom Ikan

In [50]:
#==========================================================
# FINISH LOGGING
#==========================================================

logging.info(
    "===== NOTEBOOK 02 FINISHED ====="
)

logging.shutdown()

print("NOTEBOOK 02 COMPLETED")

NOTEBOOK 02 COMPLETED

In [51]:
df[
[
    "case_id",
    "jenis_putusan",
    "retrieval_topic"
]
].head(30)

     case_id   jenis_putusan retrieval_topic
0   case_001        Bom Ikan        Bom Ikan
1   case_002           Trawl           Trawl
2   case_003           Trawl           Trawl
3   case_004      Tanpa SIPI      Tanpa SIPI
4   case_005           Trawl           Trawl
5   case_006        Bom Ikan        Bom Ikan
6   case_007      Tanpa SIUP      Tanpa SIUP
7   case_008  Perikanan Umum  Perikanan Umum
8   case_009      Tanpa SIPI      Tanpa SIPI
9   case_010        Bom Ikan        Bom Ikan
10  case_011      Tanpa SIPI      Tanpa SIPI
11  case_012           Trawl           Trawl
12  case_013           Trawl           Trawl
13  case_014     Kapal Asing     Kapal Asing
14  case_015     Kapal Asing     Kapal Asing
15  case_016      Tanpa SIPI      Tanpa SIPI
16  case_017        Bom Ikan        Bom Ikan
17  case_018      Tanpa SIPI      Tanpa SIPI
18  case_019           Trawl           Trawl
19  case_020        Bom Ikan        Bom Ikan
20  case_021      Tanpa SIPI      Tanpa SIPI
21  case_022           Trawl           Trawl
22  case_023  Perikanan Umum  Perikanan Umum
23  case_024  Perikanan Umum  Perikanan Umum
24  case_025        Bom Ikan        Bom Ikan
25  case_026      Tanpa SIPI      Tanpa SIPI
26  case_027        Bom Ikan        Bom Ikan
27  case_028      Tanpa SIPI      Tanpa SIPI
28  case_029           Trawl           Trawl
29  case_030        Bom Ikan        Bom Ikan

In [52]:
df["retrieval_topic"].value_counts()

retrieval_topic
Bom Ikan          8
Trawl             8
Tanpa SIPI        8
Perikanan Umum    3
Kapal Asing       2
Tanpa SIUP        1
Name: count, dtype: int64